"""
Tags configuration file.
Add your tags here with name, start year, and end year.
This file is standalone and does not interact with the database.
"""

TAGS = [
    {"name": "Neolithic Revolution", "start_year": -10000, "end_year": -2000},
    {"name": "Pre-Pottery Neolithic A", "start_year": -10000, "end_year": -8800},
    {"name": "Pre-Pottery Neolithic B", "start_year": -8800, "end_year": -6500},
    {"name": "Neolithic", "start_year": -7000, "end_year": -2000},
    {"name": "Chalcolithic", "start_year": -5000, "end_year": -3300},
    {"name": "Copper Age", "start_year": -5000, "end_year": -3300},
    {"name": "Bronze Age", "start_year": -3300, "end_year": -1200},
    {"name": "Early Bronze Age", "start_year": -3300, "end_year": -2100},
    {"name": "Middle Bronze Age", "start_year": -2100, "end_year": -1550},
    {"name": "Late Bronze Age", "start_year": -1550, "end_year": -1200},
    {"name": "Bronze Age Collapse", "start_year": -1200, "end_year": -1150},
    {"name": "Iron Age", "start_year": -1200, "end_year": 600},
    {"name": "Hallstatt Culture", "start_year": -1200, "end_year": -500},
    {"name": "La Tène Culture", "start_year": -450, "end_year": 1},
    {"name": "Uruk Period", "start_year": -4000, "end_year": -3100},
    {"name": "Jemdet Nasr Period", "start_year": -3100, "end_year": -2900},
    {"name": "Sumerian Civilization", "start_year": -4500, "end_year": -1900},
    {"name": "Early Dynastic Period of Mesopotamia", "start_year": -2900, "end_year": -2350},
    {"name": "Akkadian Empire", "start_year": -2334, "end_year": -2154},
    {"name": "Gutian Rule", "start_year": -2154, "end_year": -2112},
    {"name": "Third Dynasty of Ur", "start_year": -2112, "end_year": -2004},
    {"name": "Old Assyrian Period", "start_year": -2025, "end_year": -1364},
    {"name": "Middle Assyrian Empire", "start_year": -1365, "end_year": -912},
    {"name": "Neo-Assyrian Empire", "start_year": -911, "end_year": -609},
    {"name": "Neo-Babylonian Empire", "start_year": -626, "end_year": -539},
    {"name": "Babylonian Captivity", "start_year": -597, "end_year": -538},
    {"name": "Ancient Egypt Early Dynastic Period", "start_year": -3100, "end_year": -2686},
    {"name": "Old Kingdom of Egypt", "start_year": -2686, "end_year": -2181},
    {"name": "First Intermediate Period of Egypt", "start_year": -2181, "end_year": -2055},
    {"name": "Middle Kingdom of Egypt", "start_year": -2055, "end_year": -1650},
    {"name": "Second Intermediate Period of Egypt", "start_year": -1650, "end_year": -1550},
    {"name": "New Kingdom of Egypt", "start_year": -1550, "end_year": -1069},
    {"name": "Third Intermediate Period of Egypt", "start_year": -1069, "end_year": -664},
    {"name": "Late Period of Ancient Egypt", "start_year": -664, "end_year": -332},
    {"name": "Ptolemaic Kingdom", "start_year": -305, "end_year": -30},
    {"name": "Indus Valley Civilization", "start_year": -3300, "end_year": -1300},
    {"name": "Early Harappan Period", "start_year": -3300, "end_year": -2600},
    {"name": "Mature Harappan Period", "start_year": -2600, "end_year": -1900},
    {"name": "Late Harappan Period", "start_year": -1900, "end_year": -1300},
    {"name": "Minoan Civilization", "start_year": -3100, "end_year": -1100},
    {"name": "Mycenaean Civilization", "start_year": -1750, "end_year": -1050},
    {"name": "Hittite Empire", "start_year": -1650, "end_year": -1180},
    {"name": "Mitanni Kingdom", "start_year": -1500, "end_year": -1300},
    {"name": "Elamite Civilization", "start_year": -2700, "end_year": -539},
    {"name": "Shang Dynasty", "start_year": -1600, "end_year": -1046},
    {"name": "Western Zhou Dynasty", "start_year": -1046, "end_year": -771},
    {"name": "Eastern Zhou Dynasty", "start_year": -770, "end_year": -256},
    {"name": "Spring and Autumn Period", "start_year": -770, "end_year": -476},
    {"name": "Warring States Period", "start_year": -475, "end_year": -221},
    {"name": "Qin Dynasty", "start_year": -221, "end_year": -206},
    {"name": "Han Dynasty", "start_year": -202, "end_year": 220},
    {"name": "Xin Dynasty", "start_year": 9, "end_year": 23},
    {"name": "Three Kingdoms Period", "start_year": 220, "end_year": 280},
    {"name": "Western Jin Dynasty", "start_year": 266, "end_year": 316},
    {"name": "Eastern Jin Dynasty", "start_year": 317, "end_year": 420},
    {"name": "Northern and Southern Dynasties", "start_year": 420, "end_year": 589},
    {"name": "Sui Dynasty", "start_year": 581, "end_year": 618},
    {"name": "Tang Dynasty", "start_year": 618, "end_year": 907},
    {"name": "Five Dynasties and Ten Kingdoms", "start_year": 907, "end_year": 979},
    {"name": "Song Dynasty", "start_year": 960, "end_year": 1279},
    {"name": "Yuan Dynasty", "start_year": 1271, "end_year": 1368},
    {"name": "Ming Dynasty", "start_year": 1368, "end_year": 1644},
    {"name": "Qing Dynasty", "start_year": 1644, "end_year": 1912},
    {"name": "Ancient Greece", "start_year": -800, "end_year": -146},
    {"name": "Greek Dark Ages", "start_year": -1100, "end_year": -800},
    {"name": "Archaic Greece", "start_year": -800, "end_year": -480},
    {"name": "Classical Greece", "start_year": -480, "end_year": -323},
    {"name": "Hellenistic Period", "start_year": -323, "end_year": -31},
    {"name": "Persian Empire (Achaemenid)", "start_year": -550, "end_year": -330},
    {"name": "Greco-Persian Wars", "start_year": -499, "end_year": -449},
    {"name": "Peloponnesian War", "start_year": -431, "end_year": -404},
    {"name": "Corinthian War", "start_year": -395, "end_year": -387},
    {"name": "Sacred Wars", "start_year": -595, "end_year": -338},
    {"name": "Macedonian Empire", "start_year": -336, "end_year": -323},
    {"name": "Wars of the Diadochi", "start_year": -322, "end_year": -275},
    {"name": "Roman Kingdom", "start_year": -753, "end_year": -509},
    {"name": "Roman Republic", "start_year": -509, "end_year": -27},
    {"name": "Punic Wars", "start_year": -264, "end_year": -146},
    {"name": "Second Punic War", "start_year": -218, "end_year": -201},
    {"name": "Third Punic War", "start_year": -149, "end_year": -146},
    {"name": "Late Roman Republic", "start_year": -133, "end_year": -27},
    {"name": "Roman Civil Wars", "start_year": -49, "end_year": -30},
    {"name": "Roman Empire", "start_year": -27, "end_year": 476},
    {"name": "Pax Romana", "start_year": -27, "end_year": 180},
    {"name": "Crisis of the Third Century", "start_year": 235, "end_year": 284},
    {"name": "Dominate", "start_year": 284, "end_year": 476},
    {"name": "Tetrarchy", "start_year": 293, "end_year": 313},
    {"name": "Byzantine Empire", "start_year": 330, "end_year": 1453},
    {"name": "Justinianic Era", "start_year": 527, "end_year": 565},
    {"name": "Iconoclasm", "start_year": 726, "end_year": 843},
    {"name": "Great Schism", "start_year": 1054, "end_year": None},
    {"name": "Rise of Christianity", "start_year": 30, "end_year": None},
    {"name": "Early Christianity", "start_year": 30, "end_year": 313},
    {"name": "Edict of Milan", "start_year": 313, "end_year": 313},
    {"name": "Council of Nicaea", "start_year": 325, "end_year": 325},
    {"name": "Migration Period", "start_year": 300, "end_year": 700},
    {"name": "Fall of the Western Roman Empire", "start_year": 476, "end_year": 476},
    {"name": "Early Middle Ages", "start_year": 476, "end_year": 1000},
    {"name": "Merovingian Period", "start_year": 481, "end_year": 751},
    {"name": "Carolingian Empire", "start_year": 800, "end_year": 888},
    {"name": "Viking Age", "start_year": 793, "end_year": 1066},
    {"name": "Heian Period", "start_year": 794, "end_year": 1185},
    {"name": "Feudal Japan", "start_year": 1185, "end_year": 1868},
    {"name": "Kamakura Period", "start_year": 1185, "end_year": 1333},
    {"name": "Muromachi Period", "start_year": 1336, "end_year": 1573},
    {"name": "Sengoku Period", "start_year": 1467, "end_year": 1615},
    {"name": "Azuchi-Momoyama Period", "start_year": 1573, "end_year": 1603},
    {"name": "Edo Period", "start_year": 1603, "end_year": 1868},
        {"name": "First Bulgarian Empire", "start_year": 681, "end_year": 1018},
    {"name": "Abbasid Caliphate", "start_year": 750, "end_year": 1258},
    {"name": "Umayyad Caliphate", "start_year": 661, "end_year": 750},
    {"name": "Rise of Islam", "start_year": 610, "end_year": None},
    {"name": "Rashidun Caliphate", "start_year": 632, "end_year": 661},
    {"name": "Islamic Golden Age", "start_year": 750, "end_year": 1258},
    {"name": "Reconquista", "start_year": 718, "end_year": 1492},
    {"name": "Norman Conquest of England", "start_year": 1066, "end_year": 1075},
    {"name": "High Middle Ages", "start_year": 1000, "end_year": 1250},
    {"name": "Investiture Controversy", "start_year": 1075, "end_year": 1122},
    {"name": "Crusades", "start_year": 1096, "end_year": 1291},
    {"name": "First Crusade", "start_year": 1096, "end_year": 1099},
    {"name": "Second Crusade", "start_year": 1147, "end_year": 1149},
    {"name": "Third Crusade", "start_year": 1189, "end_year": 1192},
    {"name": "Fourth Crusade", "start_year": 1202, "end_year": 1204},
    {"name": "Children's Crusade", "start_year": 1212, "end_year": 1212},
    {"name": "Northern Crusades", "start_year": 1198, "end_year": 1290},
    {"name": "Albigensian Crusade", "start_year": 1209, "end_year": 1229},
    {"name": "Latin Empire", "start_year": 1204, "end_year": 1261},
    {"name": "Mongol Empire", "start_year": 1206, "end_year": 1368},
    {"name": "Mongol Invasions of Europe", "start_year": 1236, "end_year": 1242},
    {"name": "Golden Horde", "start_year": 1242, "end_year": 1502},
    {"name": "Ilkhanate", "start_year": 1256, "end_year": 1335},
    {"name": "Chagatai Khanate", "start_year": 1227, "end_year": 1687},
    {"name": "Yuan Dynasty", "start_year": 1271, "end_year": 1368},
    {"name": "Late Middle Ages", "start_year": 1250, "end_year": 1500},
    {"name": "Hundred Years' War", "start_year": 1337, "end_year": 1453},
    {"name": "Black Death", "start_year": 1346, "end_year": 1353},
    {"name": "Avignon Papacy", "start_year": 1309, "end_year": 1377},
    {"name": "Western Schism", "start_year": 1378, "end_year": 1417},
    {"name": "Hussite Wars", "start_year": 1419, "end_year": 1434},
    {"name": "Wars of the Roses", "start_year": 1455, "end_year": 1487},
    {"name": "Fall of Constantinople", "start_year": 1453, "end_year": 1453},
    {"name": "Ottoman Empire", "start_year": 1299, "end_year": 1922},
    {"name": "Ottoman Expansion", "start_year": 1354, "end_year": 1683},
    {"name": "Age of Discovery", "start_year": 1415, "end_year": 1600},
    {"name": "Portuguese Discoveries", "start_year": 1415, "end_year": 1543},
    {"name": "Spanish Colonial Empire", "start_year": 1492, "end_year": 1976},
    {"name": "Portuguese Colonial Empire", "start_year": 1415, "end_year": 1999},
    {"name": "Columbian Exchange", "start_year": 1492, "end_year": 1800},
    {"name": "Renaissance", "start_year": 1350, "end_year": 1600},
    {"name": "Early Renaissance", "start_year": 1400, "end_year": 1490},
    {"name": "High Renaissance", "start_year": 1490, "end_year": 1527},
    {"name": "Northern Renaissance", "start_year": 1430, "end_year": 1580},
    {"name": "Humanism", "start_year": 1300, "end_year": 1600},
    {"name": "Printing Revolution", "start_year": 1450, "end_year": 1600},
    {"name": "Protestant Reformation", "start_year": 1517, "end_year": 1648},
    {"name": "Counter-Reformation", "start_year": 1545, "end_year": 1648},
    {"name": "Council of Trent", "start_year": 1545, "end_year": 1563},
    {"name": "English Reformation", "start_year": 1534, "end_year": 1559},
    {"name": "French Wars of Religion", "start_year": 1562, "end_year": 1598},
    {"name": "Dutch Revolt", "start_year": 1568, "end_year": 1648},
    {"name": "Elizabethan Era", "start_year": 1558, "end_year": 1603},
    {"name": "Scientific Revolution", "start_year": 1543, "end_year": 1687},
    {"name": "Thirty Years' War", "start_year": 1618, "end_year": 1648},
    {"name": "English Civil War", "start_year": 1642, "end_year": 1651},
    {"name": "The Fronde", "start_year": 1648, "end_year": 1653},
    {"name": "Age of Absolutism", "start_year": 1643, "end_year": 1789},
    {"name": "Baroque Period", "start_year": 1600, "end_year": 1750},
    {"name": "Dutch Golden Age", "start_year": 1588, "end_year": 1672},
    {"name": "Mughal Empire", "start_year": 1526, "end_year": 1857},
    {"name": "Tokugawa Shogunate", "start_year": 1603, "end_year": 1868},
    {"name": "Great Turkish War", "start_year": 1683, "end_year": 1699},
    {"name": "Glorious Revolution", "start_year": 1688, "end_year": 1689},
    {"name": "Age of Enlightenment", "start_year": 1685, "end_year": 1815},
    {"name": "Great Northern War", "start_year": 1700, "end_year": 1721},
    {"name": "War of the Spanish Succession", "start_year": 1701, "end_year": 1714},
    {"name": "Rococo Period", "start_year": 1730, "end_year": 1770},
    {"name": "Seven Years' War", "start_year": 1756, "end_year": 1763},
    {"name": "Industrial Revolution", "start_year": 1760, "end_year": 1840},
    {"name": "American Revolution", "start_year": 1765, "end_year": 1783},
    {"name": "American Revolutionary War", "start_year": 1775, "end_year": 1783},
    {"name": "French Revolution", "start_year": 1789, "end_year": 1799},
    {"name": "Reign of Terror", "start_year": 1793, "end_year": 1794},
    {"name": "Directory", "start_year": 1795, "end_year": 1799},
    {"name": "Napoleonic Era", "start_year": 1799, "end_year": 1815},
    {"name": "Napoleonic Wars", "start_year": 1803, "end_year": 1815},
    {"name": "Peninsular War", "start_year": 1807, "end_year": 1814},
    {"name": "Congress of Vienna", "start_year": 1814, "end_year": 1815},
    {"name": "Concert of Europe", "start_year": 1815, "end_year": 1914},
    {"name": "Romanticism", "start_year": 1798, "end_year": 1850},
    {"name": "Greek War of Independence", "start_year": 1821, "end_year": 1829},
    {"name": "First Industrial Revolution", "start_year": 1760, "end_year": 1840},
    {"name": "Second Industrial Revolution", "start_year": 1870, "end_year": 1914},
    {"name": "Victorian Era", "start_year": 1837, "end_year": 1901},
    {"name": "Revolutions of 1848", "start_year": 1848, "end_year": 1849},
    {"name": "Crimean War", "start_year": 1853, "end_year": 1856},
    {"name": "American Civil War", "start_year": 1861, "end_year": 1865},
    {"name": "Italian Unification", "start_year": 1815, "end_year": 1871},
    {"name": "German Unification", "start_year": 1864, "end_year": 1871},
    {"name": "Meiji Restoration", "start_year": 1868, "end_year": 1912},
    {"name": "Belle Époque", "start_year": 1871, "end_year": 1914},
    {"name": "Imperialism", "start_year": 1870, "end_year": 1914},
    {"name": "Scramble for Africa", "start_year": 1881, "end_year": 1914},
    {"name": "Boer Wars", "start_year": 1880, "end_year": 1902},
    {"name": "First Boer War", "start_year": 1880, "end_year": 1881},
    {"name": "Second Boer War", "start_year": 1899, "end_year": 1902},
    {"name": "Boxer Rebellion", "start_year": 1899, "end_year": 1901},
    {"name": "Progressive Era", "start_year": 1890, "end_year": 1920},
        {"name": "Mamluk Sultanate", "start_year": 1250, "end_year": 1517},
    {"name": "Serbian Empire", "start_year": 1346, "end_year": 1371},
    {"name": "Polish-Lithuanian Union", "start_year": 1385, "end_year": 1569},
    {"name": "Kingdom of Portugal Expansion", "start_year": 1415, "end_year": 1580},
    {"name": "Ming Dynasty Maritime Expeditions", "start_year": 1405, "end_year": 1433},
    {"name": "Timurid Empire", "start_year": 1370, "end_year": 1507},
    {"name": "Ottoman Conquest of Constantinople", "start_year": 1453, "end_year": 1453},
    {"name": "Aztec Empire", "start_year": 1428, "end_year": 1521},
    {"name": "Inca Empire", "start_year": 1438, "end_year": 1533},
    {"name": "Maya Postclassic Period", "start_year": 900, "end_year": 1697},
    {"name": "Songhai Empire", "start_year": 1464, "end_year": 1591},
    {"name": "Kingdom of Kongo", "start_year": 1390, "end_year": 1914},
    {"name": "Mali Empire", "start_year": 1235, "end_year": 1600},
    {"name": "Swahili City States", "start_year": 1000, "end_year": 1500},
    {"name": "Portuguese Empire", "start_year": 1415, "end_year": 1999},
    {"name": "Spanish Empire", "start_year": 1492, "end_year": 1976},
    {"name": "French Colonial Empire", "start_year": 1534, "end_year": 1980},
    {"name": "Dutch Colonial Empire", "start_year": 1602, "end_year": 1975},
    {"name": "British Empire Expansion", "start_year": 1607, "end_year": 1997},
    {"name": "Atlantic Slave Trade Era", "start_year": 1501, "end_year": 1867},
    {"name": "Triangular Trade", "start_year": 1500, "end_year": 1800},
    {"name": "European Colonialism", "start_year": 1500, "end_year": 1975},
    {"name": "Age of Mercantilism", "start_year": 1500, "end_year": 1800},
    {"name": "Habsburg Spain", "start_year": 1516, "end_year": 1700},
    {"name": "Spanish Conquest of the Americas", "start_year": 1519, "end_year": 1697},
    {"name": "Italian Wars", "start_year": 1494, "end_year": 1559},
    {"name": "War of the League of Cambrai", "start_year": 1508, "end_year": 1516},
    {"name": "Ottoman-Safavid War", "start_year": 1514, "end_year": 1555},
    {"name": "Safavid Dynasty", "start_year": 1501, "end_year": 1736},
    {"name": "Mughal-Safavid Conflicts", "start_year": 1510, "end_year": 1747},
    {"name": "Knights Hospitaller in Malta", "start_year": 1530, "end_year": 1798},
    {"name": "Siege of Malta", "start_year": 1565, "end_year": 1565},
    {"name": "Anglo-Spanish War", "start_year": 1585, "end_year": 1604},
    {"name": "Eighty Years' War", "start_year": 1568, "end_year": 1648},
    {"name": "Polish-Swedish War", "start_year": 1600, "end_year": 1629},
    {"name": "Smolensk War", "start_year": 1632, "end_year": 1634},
    {"name": "Khmelnytsky Uprising", "start_year": 1648, "end_year": 1657},
    {"name": "Northern Wars", "start_year": 1655, "end_year": 1721},
    {"name": "Franco-Dutch War", "start_year": 1672, "end_year": 1678},
    {"name": "Nine Years' War", "start_year": 1688, "end_year": 1697},
    {"name": "War of the Grand Alliance", "start_year": 1688, "end_year": 1697},
    {"name": "War of Jenkins' Ear", "start_year": 1739, "end_year": 1748},
    {"name": "War of Austrian Succession", "start_year": 1740, "end_year": 1748},
    {"name": "Carnatic Wars", "start_year": 1746, "end_year": 1763},
    {"name": "Peshwa Period of Maratha Empire", "start_year": 1713, "end_year": 1818},
    {"name": "Maratha Empire", "start_year": 1674, "end_year": 1818},
    {"name": "First Anglo-Maratha War", "start_year": 1775, "end_year": 1782},
    {"name": "Second Anglo-Maratha War", "start_year": 1803, "end_year": 1805},
    {"name": "Third Anglo-Maratha War", "start_year": 1817, "end_year": 1818},
    {"name": "Mysore Wars", "start_year": 1767, "end_year": 1799},
    {"name": "First Anglo-Mysore War", "start_year": 1767, "end_year": 1769},
    {"name": "Second Anglo-Mysore War", "start_year": 1780, "end_year": 1784},
    {"name": "Third Anglo-Mysore War", "start_year": 1790, "end_year": 1792},
    {"name": "Fourth Anglo-Mysore War", "start_year": 1799, "end_year": 1799},
    {"name": "Haitian Revolution", "start_year": 1791, "end_year": 1804},
    {"name": "Latin American Wars of Independence", "start_year": 1808, "end_year": 1833},
    {"name": "Mexican War of Independence", "start_year": 1810, "end_year": 1821},
    {"name": "Gran Colombia", "start_year": 1819, "end_year": 1831},
    {"name": "Brazilian Independence", "start_year": 1822, "end_year": 1822},
    {"name": "Greek Civil War of Independence Period", "start_year": 1821, "end_year": 1832},
    {"name": "First Anglo-Afghan War", "start_year": 1839, "end_year": 1842},
    {"name": "Taiping Rebellion", "start_year": 1850, "end_year": 1864},
    {"name": "Second Opium War", "start_year": 1856, "end_year": 1860},
    {"name": "Indian Rebellion of 1857", "start_year": 1857, "end_year": 1858},
    {"name": "French Intervention in Mexico", "start_year": 1861, "end_year": 1867},
    {"name": "Second Schleswig War", "start_year": 1864, "end_year": 1864},
    {"name": "Franco-Prussian War", "start_year": 1870, "end_year": 1871},
    {"name": "Paris Commune", "start_year": 1871, "end_year": 1871},
    {"name": "Zulu War", "start_year": 1879, "end_year": 1879},
    {"name": "First Sino-Japanese War", "start_year": 1894, "end_year": 1895},
    {"name": "Spanish-American War", "start_year": 1898, "end_year": 1898},
    {"name": "Philippine-American War", "start_year": 1899, "end_year": 1902},
    {"name": "Russo-Japanese War", "start_year": 1904, "end_year": 1905},
    {"name": "Mexican Revolution", "start_year": 1910, "end_year": 1920},
    {"name": "Xinhai Revolution", "start_year": 1911, "end_year": 1912},
    {"name": "Balkan Wars", "start_year": 1912, "end_year": 1913},
    {"name": "First Balkan War", "start_year": 1912, "end_year": 1913},
    {"name": "Second Balkan War", "start_year": 1913, "end_year": 1913},
    {"name": "World War I", "start_year": 1914, "end_year": 1918},
    {"name": "Western Front of World War I", "start_year": 1914, "end_year": 1918},
    {"name": "Eastern Front of World War I", "start_year": 1914, "end_year": 1918},
    {"name": "Gallipoli Campaign", "start_year": 1915, "end_year": 1916},
    {"name": "Russian Revolution", "start_year": 1917, "end_year": 1917},
    {"name": "Russian Civil War", "start_year": 1917, "end_year": 1923},
    {"name": "Soviet Union Formation", "start_year": 1922, "end_year": 1991},
    {"name": "Weimar Republic", "start_year": 1919, "end_year": 1933},
    {"name": "Irish War of Independence", "start_year": 1919, "end_year": 1921},
    {"name": "Irish Civil War", "start_year": 1922, "end_year": 1923},
    {"name": "Chinese Civil War", "start_year": 1927, "end_year": 1949},
    {"name": "Great Depression", "start_year": 1929, "end_year": 1939},
    {"name": "Fascist Italy", "start_year": 1922, "end_year": 1943},
    {"name": "Nazi Germany", "start_year": 1933, "end_year": 1945},
    {"name": "Spanish Civil War", "start_year": 1936, "end_year": 1939},
    {"name": "Second Sino-Japanese War", "start_year": 1937, "end_year": 1945},
    {"name": "World War II", "start_year": 1939, "end_year": 1945},
    {"name": "Eastern Front World War II", "start_year": 1941, "end_year": 1945},
    {"name": "Pacific War", "start_year": 1941, "end_year": 1945},
    {"name": "Battle of Stalingrad", "start_year": 1942, "end_year": 1943},
    {"name": "Holocaust", "start_year": 1941, "end_year": 1945},
    {"name": "Nuremberg Trials", "start_year": 1945, "end_year": 1946},
    {"name": "United Nations Era", "start_year": 1945, "end_year": None},
    {"name": "Decolonization Era", "start_year": 1945, "end_year": 1975},
    {"name": "Indian Independence Movement", "start_year": 1857, "end_year": 1947},
    {"name": "Partition of India", "start_year": 1947, "end_year": 1947},
    {"name": "First Arab-Israeli War", "start_year": 1948, "end_year": 1949},
    {"name": "Chinese Communist Revolution", "start_year": 1946, "end_year": 1949},
    {"name": "Korean War", "start_year": 1950, "end_year": 1953},
    {"name": "Algerian War of Independence", "start_year": 1954, "end_year": 1962},
    {"name": "Vietnam War", "start_year": 1955, "end_year": 1975},
    {"name": "Hungarian Revolution of 1956", "start_year": 1956, "end_year": 1956},
    {"name": "Cuban Revolution", "start_year": 1953, "end_year": 1959},
    {"name": "Cold War", "start_year": 1947, "end_year": 1991},
    {"name": "Space Race", "start_year": 1955, "end_year": 1975},
    {"name": "Cultural Revolution in China", "start_year": 1966, "end_year": 1976},
    {"name": "Prague Spring", "start_year": 1968, "end_year": 1968},
    {"name": "Six-Day War", "start_year": 1967, "end_year": 1967},
    {"name": "Yom Kippur War", "start_year": 1973, "end_year": 1973},
    {"name": "Iranian Revolution", "start_year": 1978, "end_year": 1979},
    {"name": "Soviet-Afghan War", "start_year": 1979, "end_year": 1989},
    {"name": "Falklands War", "start_year": 1982, "end_year": 1982},
    {"name": "Lebanese Civil War", "start_year": 1975, "end_year": 1990},
    {"name": "Gulf War", "start_year": 1990, "end_year": 1991},
    {"name": "Dissolution of Yugoslavia", "start_year": 1991, "end_year": 2008},
    {"name": "Yugoslav Wars", "start_year": 1991, "end_year": 2001},
    {"name": "Rwandan Genocide", "start_year": 1994, "end_year": 1994},
    {"name": "First Congo War", "start_year": 1996, "end_year": 1997},
    {"name": "Second Congo War", "start_year": 1998, "end_year": 2003},
    {"name": "War on Terror", "start_year": 2001, "end_year": None},
    {"name": "Afghanistan War", "start_year": 2001, "end_year": 2021},
    {"name": "Iraq War", "start_year": 2003, "end_year": 2011},
    {"name": "Arab Spring", "start_year": 2010, "end_year": 2012},
    {"name": "Syrian Civil War", "start_year": 2011, "end_year": None},
    {"name": "Russo-Ukrainian War", "start_year": 2014, "end_year": None},
    {"name": "COVID-19 Pandemic Era", "start_year": 2019, "end_year": 2023},
]

def get_tags():
    """Return the list of tags."""
    return TAGS

if __name__ == "__main__":
    if not TAGS:
        print("No tags configured. Please edit the TAGS list in this file.")
        print("Example format:")
        print('TAGS = [')
        print('    {"name": "World War II", "start_year": 1939, "end_year": 1945},')
        print('    {"name": "Cold War", "start_year": 1947, "end_year": 1991},')
        print(']')
    else:
        print(f"Loaded {len(TAGS)} tags:")
        for tag in TAGS:
            print(f"  - {tag['name']} ({tag.get('start_year')} - {tag.get('end_year')})")
