import sys
import os

# Add the parent directory to the path so we can import backend modules
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from frontend.app import app
from backend.models.model import Tag

HISTORICAL_TAGS = [
    "Egyptian New Kingdom Expansion",
    "Bronze Age Collapse",
    "Sea Peoples Invasions",
    "Neo-Assyrian Expansion",
    "Fall of the Neo-Assyrian Empire",
    "Neo-Babylonian Empire",
    "Achaemenid Expansion",
    "Ionian Revolt",
    "Greco-Persian Wars",
    "Peloponnesian War",
    "Corinthian War",
    "Spartan Hegemony",
    "Theban Hegemony",
    "Sacred Wars",
    "Rise of Macedon",
    "Conquests of Alexander the Great",
    "Wars of the Diadochi",
    "Gallic Invasions",
    "Pyrrhic War",
    "Roman Conquest of Italy",
    "Samnite Wars",
    "Latin War",
    "Punic Wars",
    "Roman Conquest of Greece",
    "Roman Conquest of Hispania",
    "Roman Conquest of Gaul",
    "Mithridatic Wars",
    "Social War",
    "Servile Wars",
    "Caesar's Civil War",
    "Liberators' Civil War",
    "Final War of the Roman Republic",
    "Roman Conquest of Britain",
    "Roman–Parthian Wars",
    "Jewish–Roman Wars",
    "Marcomannic Wars",
    "Crisis of the Third Century",
    "Roman–Sassanian Wars",
    "Gothic Wars",
    "Barbarian Invasions",
    "Hunnic Invasions",
    "Rise of Christianity",
    "Byzantine–Persian Wars",
    "Justinian's Reconquests",
    "Rise of Islam",
    "Islamic Conquests",
    "First Fitna",
    "Second Fitna",
    "Abbasid Revolution",
    "Viking Age",
    "Magyar Invasions",
    "Norman Conquests",
    "Reconquista",
    "Crusades",
    "Mongol Conquests",
    "Mongol Invasion of Europe",
    "Mongol Conquest of China",
    "Black Death",
    "Hundred Years' War",
    "Wars of the Roses",
    "Ottoman Expansion",
    "Byzantine–Ottoman Wars",
    "Fall of the Byzantine Empire",
    "Timurid Conquests",
    "Renaissance",
    "Age of Exploration",
    "Columbian Exchange",
    "Protestant Reformation",
    "Counter-Reformation",
    "European Wars of Religion",
    "Dutch Revolt",
    "Eighty Years' War",
    "French Wars of Religion",
    "Scientific Revolution",
    "Thirty Years' War",
    "English Civil Wars",
    "Fronde",
    "Great Turkish War",
    "Great Northern War",
    "War of the Spanish Succession",
    "War of the Austrian Succession",
    "Seven Years' War",
    "Partitions of Poland",
    "American Revolution",
    "French Revolution",
    "Haitian Revolution",
    "Napoleonic Wars",
    "Congress of Vienna",
    "Concert of Europe",
    "Greek War of Independence",
    "Latin American Wars of Independence",
    "Industrial Revolution",
    "Belgian Revolution",
    "Revolutions of 1848",
    "Crimean War",
    "Taiping Rebellion",
    "Indian Rebellion of 1857",
    "Meiji Restoration",
    "American Civil War",
    "Unification of Italy",
    "Unification of Germany",
    "Franco-Prussian War",
    "Long Depression",
    "Scramble for Africa",
    "New Imperialism",
    "Boxer Rebellion",
    "Russo-Japanese War",
    "Mexican Revolution",
    "Balkan Wars",
    "First World War",
    "Armenian Genocide",
    "Russian Revolution",
    "Russian Civil War",
    "Interwar Period",
    "Irish War of Independence",
    "Rise of Fascism",
    "Great Depression",
    "Spanish Civil War",
    "Second Sino-Japanese War",
    "Second World War",
    "Holocaust",
    "Chinese Civil War",
    "Partition of India",
    "Arab–Israeli Conflict",
    "Korean War",
    "Cold War",
    "Decolonization",
    "Suez Crisis",
    "Cuban Revolution",
    "Space Race",
    "Vietnam War",
    "Cultural Revolution",
    "Prague Spring",
    "Six-Day War",
    "Yom Kippur War",
    "Iranian Revolution",
    "Soviet–Afghan War",
    "Iran–Iraq War",
    "Falklands War",
    "Solidarity Movement",
    "Revolutions of 1989",
    "Dissolution of Yugoslavia",
    "Gulf War",
    "Collapse of the Soviet Union",
    "Rwandan Genocide",
    "Yugoslav Wars",
    "First Congo War",
    "Second Congo War",
    "War on Terror",
    "September 11 Attacks",
    "Afghanistan War",
    "Iraq War",
    "Arab Spring",
    "Syrian Civil War",
    "Russian Invasion of Crimea",
    "COVID-19 Pandemic",
    "Russian Invasion of Ukraine",
    "Digital Revolution",
    "Information Age",
    "Globalization",
    "European Integration",
    "Decolonization of Africa",
    "Decolonization of Asia",
    "Green Revolution",
    "Nuclear Arms Race",
    "Space Exploration Era",
    "Age of Discovery",
    "Commercial Revolution",
    "Military Revolution",
    "Enlightenment",
    "Age of Absolutism",
    "Pax Romana",
    "Pax Mongolica",
    "Pax Britannica",
    "Gilded Age",
    "Progressive Era",
    "Roaring Twenties",
    "Postwar Economic Boom",
    "Civil Rights Movement",
    "Feminist Movement",
    "Anti-Apartheid Movement",
    "Chinese Economic Reforms",
    "Glasnost and Perestroika",
    "European Migration Crisis",
    "Global Financial Crisis",
    "COVID Economic Crisis"
]

def populate_tags():
    from backend.models.model import db
    with app.app_context():
        # Check if tags already exist
        existing_tags = Tag.query.all()
        if existing_tags:
            print(f"Found {len(existing_tags)} existing tags in database.")
            response = input("Do you want to clear existing tags and repopulate? (y/n): ")
            if response.lower() == 'y':
                Tag.query.delete()
                db.session.commit()
                print("Cleared existing tags.")
            else:
                print("Aborting. No changes made.")
                return
        
        # Add new tags
        for tag_name in HISTORICAL_TAGS:
            tag = Tag(name=tag_name)
            db.session.add(tag)
        
        db.session.commit()
        print(f"Successfully added {len(HISTORICAL_TAGS)} historical tags to the database.")

if __name__ == "__main__":
    populate_tags()
