import sys
import os

# Add the parent directory to the path so we can import backend modules
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from frontend.app import app
from backend.models.model import Tag

HISTORICAL_TAGS = [
    {"name": "Egyptian New Kingdom Expansion", "start_year": 1550, "end_year": 1077},
    {"name": "Bronze Age Collapse", "start_year": 1200, "end_year": 1150},
    {"name": "Sea Peoples Invasions", "start_year": 1200, "end_year": 1150},
    {"name": "Neo-Assyrian Expansion", "start_year": 911, "end_year": 609},
    {"name": "Fall of the Neo-Assyrian Empire", "start_year": 615, "end_year": 609},
    {"name": "Neo-Babylonian Empire", "start_year": 626, "end_year": 539},
    {"name": "Achaemenid Expansion", "start_year": 550, "end_year": 330},
    {"name": "Ionian Revolt", "start_year": 499, "end_year": 493},
    {"name": "Greco-Persian Wars", "start_year": 499, "end_year": 449},
    {"name": "Peloponnesian War", "start_year": 431, "end_year": 404},
    {"name": "Corinthian War", "start_year": 395, "end_year": 387},
    {"name": "Spartan Hegemony", "start_year": 404, "end_year": 371},
    {"name": "Theban Hegemony", "start_year": 371, "end_year": 362},
    {"name": "Sacred Wars", "start_year": 595, "end_year": 346},
    {"name": "Rise of Macedon", "start_year": 359, "end_year": 336},
    {"name": "Conquests of Alexander the Great", "start_year": 336, "end_year": 323},
    {"name": "Wars of the Diadochi", "start_year": 322, "end_year": 281},
    {"name": "Gallic Invasions", "start_year": 390, "end_year": 51},
    {"name": "Pyrrhic War", "start_year": 280, "end_year": 275},
    {"name": "Roman Conquest of Italy", "start_year": 343, "end_year": 272},
    {"name": "Samnite Wars", "start_year": 343, "end_year": 290},
    {"name": "Latin War", "start_year": 340, "end_year": 338},
    {"name": "Punic Wars", "start_year": 264, "end_year": 146},
    {"name": "Roman Conquest of Greece", "start_year": 214, "end_year": 146},
    {"name": "Roman Conquest of Hispania", "start_year": 218, "end_year": 19},
    {"name": "Roman Conquest of Gaul", "start_year": 58, "end_year": 50},
    {"name": "Mithridatic Wars", "start_year": 88, "end_year": 63},
    {"name": "Social War", "start_year": 91, "end_year": 88},
    {"name": "Servile Wars", "start_year": 135, "end_year": 71},
    {"name": "Caesar's Civil War", "start_year": 49, "end_year": 45},
    {"name": "Liberators' Civil War", "start_year": 43, "end_year": 42},
    {"name": "Final War of the Roman Republic", "start_year": 32, "end_year": 30},
    {"name": "Roman Conquest of Britain", "start_year": 43, "end_year": 410},
    {"name": "Roman–Parthian Wars", "start_year": 66, "end_year": 217},
    {"name": "Jewish–Roman Wars", "start_year": 66, "end_year": 135},
    {"name": "Marcomannic Wars", "start_year": 166, "end_year": 180},
    {"name": "Crisis of the Third Century", "start_year": 235, "end_year": 284},
    {"name": "Roman–Sassanian Wars", "start_year": 230, "end_year": 628},
    {"name": "Gothic Wars", "start_year": 249, "end_year": 554},
    {"name": "Barbarian Invasions", "start_year": 300, "end_year": 500},
    {"name": "Hunnic Invasions", "start_year": 370, "end_year": 469},
    {"name": "Rise of Christianity", "start_year": 30, "end_year": 380},
    {"name": "Byzantine–Persian Wars", "start_year": 502, "end_year": 628},
    {"name": "Justinian's Reconquests", "start_year": 533, "end_year": 554},
    {"name": "Rise of Islam", "start_year": 610, "end_year": 632},
    {"name": "Islamic Conquests", "start_year": 632, "end_year": 750},
    {"name": "First Fitna", "start_year": 656, "end_year": 661},
    {"name": "Second Fitna", "start_year": 680, "end_year": 692},
    {"name": "Abbasid Revolution", "start_year": 747, "end_year": 750},
    {"name": "Viking Age", "start_year": 793, "end_year": 1066},
    {"name": "Magyar Invasions", "start_year": 895, "end_year": 955},
    {"name": "Norman Conquests", "start_year": 999, "end_year": 1150},
    {"name": "Reconquista", "start_year": 718, "end_year": 1492},
    {"name": "Crusades", "start_year": 1095, "end_year": 1291},
    {"name": "Mongol Conquests", "start_year": 1206, "end_year": 1324},
    {"name": "Mongol Invasion of Europe", "start_year": 1236, "end_year": 1242},
    {"name": "Mongol Conquest of China", "start_year": 1205, "end_year": 1279},
    {"name": "Black Death", "start_year": 1346, "end_year": 1353},
    {"name": "Hundred Years' War", "start_year": 1337, "end_year": 1453},
    {"name": "Wars of the Roses", "start_year": 1455, "end_year": 1487},
    {"name": "Ottoman Expansion", "start_year": 1299, "end_year": 1683},
    {"name": "Byzantine–Ottoman Wars", "start_year": 1265, "end_year": 1479},
    {"name": "Fall of the Byzantine Empire", "start_year": 1453, "end_year": 1453},
    {"name": "Timurid Conquests", "start_year": 1370, "end_year": 1507},
    {"name": "Renaissance", "start_year": 1300, "end_year": 1600},
    {"name": "Age of Exploration", "start_year": 1415, "end_year": 1800},
    {"name": "Columbian Exchange", "start_year": 1492, "end_year": 1800},
    {"name": "Protestant Reformation", "start_year": 1517, "end_year": 1648},
    {"name": "Counter-Reformation", "start_year": 1545, "end_year": 1648},
    {"name": "European Wars of Religion", "start_year": 1524, "end_year": 1648},
    {"name": "Dutch Revolt", "start_year": 1566, "end_year": 1648},
    {"name": "Eighty Years' War", "start_year": 1568, "end_year": 1648},
    {"name": "French Wars of Religion", "start_year": 1562, "end_year": 1598},
    {"name": "Scientific Revolution", "start_year": 1543, "end_year": 1687},
    {"name": "Thirty Years' War", "start_year": 1618, "end_year": 1648},
    {"name": "English Civil Wars", "start_year": 1642, "end_year": 1651},
    {"name": "Fronde", "start_year": 1648, "end_year": 1653},
    {"name": "Great Turkish War", "start_year": 1683, "end_year": 1699},
    {"name": "Great Northern War", "start_year": 1700, "end_year": 1721},
    {"name": "War of the Spanish Succession", "start_year": 1701, "end_year": 1714},
    {"name": "War of the Austrian Succession", "start_year": 1740, "end_year": 1748},
    {"name": "Seven Years' War", "start_year": 1756, "end_year": 1763},
    {"name": "Partitions of Poland", "start_year": 1772, "end_year": 1795},
    {"name": "American Revolution", "start_year": 1765, "end_year": 1783},
    {"name": "French Revolution", "start_year": 1789, "end_year": 1799},
    {"name": "Haitian Revolution", "start_year": 1791, "end_year": 1804},
    {"name": "Napoleonic Wars", "start_year": 1803, "end_year": 1815},
    {"name": "Congress of Vienna", "start_year": 1814, "end_year": 1815},
    {"name": "Concert of Europe", "start_year": 1815, "end_year": 1914},
    {"name": "Greek War of Independence", "start_year": 1821, "end_year": 1829},
    {"name": "Latin American Wars of Independence", "start_year": 1808, "end_year": 1833},
    {"name": "Industrial Revolution", "start_year": 1760, "end_year": 1840},
    {"name": "Belgian Revolution", "start_year": 1830, "end_year": 1831},
    {"name": "Revolutions of 1848", "start_year": 1848, "end_year": 1849},
    {"name": "Crimean War", "start_year": 1853, "end_year": 1856},
    {"name": "Taiping Rebellion", "start_year": 1850, "end_year": 1864},
    {"name": "Indian Rebellion of 1857", "start_year": 1857, "end_year": 1858},
    {"name": "Meiji Restoration", "start_year": 1868, "end_year": 1869},
    {"name": "American Civil War", "start_year": 1861, "end_year": 1865},
    {"name": "Unification of Italy", "start_year": 1859, "end_year": 1871},
    {"name": "Unification of Germany", "start_year": 1864, "end_year": 1871},
    {"name": "Franco-Prussian War", "start_year": 1870, "end_year": 1871},
    {"name": "Long Depression", "start_year": 1873, "end_year": 1896},
    {"name": "Scramble for Africa", "start_year": 1881, "end_year": 1914},
    {"name": "New Imperialism", "start_year": 1870, "end_year": 1914},
    {"name": "Boxer Rebellion", "start_year": 1899, "end_year": 1901},
    {"name": "Russo-Japanese War", "start_year": 1904, "end_year": 1905},
    {"name": "Mexican Revolution", "start_year": 1910, "end_year": 1920},
    {"name": "Balkan Wars", "start_year": 1912, "end_year": 1913},
    {"name": "First World War", "start_year": 1914, "end_year": 1918},
    {"name": "Armenian Genocide", "start_year": 1915, "end_year": 1917},
    {"name": "Russian Revolution", "start_year": 1917, "end_year": 1923},
    {"name": "Russian Civil War", "start_year": 1917, "end_year": 1922},
    {"name": "Interwar Period", "start_year": 1918, "end_year": 1939},
    {"name": "Irish War of Independence", "start_year": 1919, "end_year": 1921},
    {"name": "Rise of Fascism", "start_year": 1919, "end_year": 1945},
    {"name": "Great Depression", "start_year": 1929, "end_year": 1939},
    {"name": "Spanish Civil War", "start_year": 1936, "end_year": 1939},
    {"name": "Second Sino-Japanese War", "start_year": 1937, "end_year": 1945},
    {"name": "Second World War", "start_year": 1939, "end_year": 1945},
    {"name": "Holocaust", "start_year": 1941, "end_year": 1945},
    {"name": "Chinese Civil War", "start_year": 1927, "end_year": 1949},
    {"name": "Partition of India", "start_year": 1947, "end_year": 1947},
    {"name": "Arab–Israeli Conflict", "start_year": 1948, "end_year": None},
    {"name": "Korean War", "start_year": 1950, "end_year": 1953},
    {"name": "Cold War", "start_year": 1947, "end_year": 1991},
    {"name": "Decolonization", "start_year": 1945, "end_year": 1975},
    {"name": "Suez Crisis", "start_year": 1956, "end_year": 1957},
    {"name": "Cuban Revolution", "start_year": 1953, "end_year": 1959},
    {"name": "Space Race", "start_year": 1955, "end_year": 1975},
    {"name": "Vietnam War", "start_year": 1955, "end_year": 1975},
    {"name": "Cultural Revolution", "start_year": 1966, "end_year": 1976},
    {"name": "Prague Spring", "start_year": 1968, "end_year": 1968},
    {"name": "Six-Day War", "start_year": 1967, "end_year": 1967},
    {"name": "Yom Kippur War", "start_year": 1973, "end_year": 1973},
    {"name": "Iranian Revolution", "start_year": 1978, "end_year": 1979},
    {"name": "Soviet–Afghan War", "start_year": 1979, "end_year": 1989},
    {"name": "Iran–Iraq War", "start_year": 1980, "end_year": 1988},
    {"name": "Falklands War", "start_year": 1982, "end_year": 1982},
    {"name": "Solidarity Movement", "start_year": 1980, "end_year": 1989},
    {"name": "Revolutions of 1989", "start_year": 1989, "end_year": 1989},
    {"name": "Dissolution of Yugoslavia", "start_year": 1991, "end_year": 2001},
    {"name": "Gulf War", "start_year": 1990, "end_year": 1991},
    {"name": "Collapse of the Soviet Union", "start_year": 1991, "end_year": 1991},
    {"name": "Rwandan Genocide", "start_year": 1994, "end_year": 1994},
    {"name": "Yugoslav Wars", "start_year": 1991, "end_year": 2001},
    {"name": "First Congo War", "start_year": 1996, "end_year": 1997},
    {"name": "Second Congo War", "start_year": 1998, "end_year": 2003},
    {"name": "War on Terror", "start_year": 2001, "end_year": None},
    {"name": "September 11 Attacks", "start_year": 2001, "end_year": 2001},
    {"name": "Afghanistan War", "start_year": 2001, "end_year": 2021},
    {"name": "Iraq War", "start_year": 2003, "end_year": 2011},
    {"name": "Arab Spring", "start_year": 2010, "end_year": 2012},
    {"name": "Syrian Civil War", "start_year": 2011, "end_year": None},
    {"name": "Russian Invasion of Crimea", "start_year": 2014, "end_year": 2014},
    {"name": "COVID-19 Pandemic", "start_year": 2019, "end_year": 2023},
    {"name": "Russian Invasion of Ukraine", "start_year": 2022, "end_year": None},
    {"name": "Digital Revolution", "start_year": 1950, "end_year": None},
    {"name": "Information Age", "start_year": 1970, "end_year": None},
    {"name": "Globalization", "start_year": 1980, "end_year": None},
    {"name": "European Integration", "start_year": 1951, "end_year": None},
    {"name": "Decolonization of Africa", "start_year": 1957, "end_year": 1975},
    {"name": "Decolonization of Asia", "start_year": 1945, "end_year": 1965},
    {"name": "Green Revolution", "start_year": 1940, "end_year": 1970},
    {"name": "Nuclear Arms Race", "start_year": 1945, "end_year": 1991},
    {"name": "Space Exploration Era", "start_year": 1957, "end_year": None},
    {"name": "Age of Discovery", "start_year": 1415, "end_year": 1800},
    {"name": "Commercial Revolution", "start_year": 1100, "end_year": 1800},
    {"name": "Military Revolution", "start_year": 1500, "end_year": 1800},
    {"name": "Enlightenment", "start_year": 1685, "end_year": 1815},
    {"name": "Age of Absolutism", "start_year": 1600, "end_year": 1800},
    {"name": "Pax Romana", "start_year": 27, "end_year": 180},
    {"name": "Pax Mongolica", "start_year": 1279, "end_year": 1368},
    {"name": "Pax Britannica", "start_year": 1815, "end_year": 1914},
    {"name": "Gilded Age", "start_year": 1870, "end_year": 1900},
    {"name": "Progressive Era", "start_year": 1890, "end_year": 1920},
    {"name": "Roaring Twenties", "start_year": 1920, "end_year": 1929},
    {"name": "Postwar Economic Boom", "start_year": 1945, "end_year": 1973},
    {"name": "Civil Rights Movement", "start_year": 1954, "end_year": 1968},
    {"name": "Feminist Movement", "start_year": 1960, "end_year": None},
    {"name": "Anti-Apartheid Movement", "start_year": 1948, "end_year": 1994},
    {"name": "Chinese Economic Reforms", "start_year": 1978, "end_year": None},
    {"name": "Glasnost and Perestroika", "start_year": 1985, "end_year": 1991},
    {"name": "European Migration Crisis", "start_year": 2015, "end_year": 2016},
    {"name": "Global Financial Crisis", "start_year": 2007, "end_year": 2009},
    {"name": "COVID Economic Crisis", "start_year": 2020, "end_year": 2022}
]

def populate_tags():
    from backend.models.model import db
    with app.app_context():
        # Check if tags already exist
        existing_tags = Tag.query.all()
        if existing_tags:
            print(f"Found {len(existing_tags)} existing tags in database.")
            response = input("Do you want to clear existing tags and repopulate? (y/n): ")
            if response.lower() == 'y':
                Tag.query.delete()
                db.session.commit()
                print("Cleared existing tags.")
            else:
                print("Aborting. No changes made.")
                return
        
        # Add new tags
        for tag_data in HISTORICAL_TAGS:
            tag = Tag(
                name=tag_data["name"],
                start_year=tag_data.get("start_year"),
                end_year=tag_data.get("end_year")
            )
            db.session.add(tag)
        
        db.session.commit()
        print(f"Successfully added {len(HISTORICAL_TAGS)} historical tags to the database.")

if __name__ == "__main__":
    populate_tags()
